name: markdown

on: workflow_call

jobs:
  extract-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract app version
        id: extract_version
        run: |
          app_version=$(grep '^version=' "./project.properties" | cut -d'=' -f2)
          echo "App Version: ${app_version}"
          echo "APP_VERSION=${app_version}" >> "$GITHUB_ENV"

      - name: Extract python version
        id: extract_python_version
        run: |
          python_version=$(grep '^python-version=' "./project.properties" | cut -d'=' -f2)
          echo "Python Version: ${python_version}"
          echo "PYTHON_VERSION=${python_version}" >> "$GITHUB_ENV"

  flake8-lint:
    runs-on: ubuntu-latest
    needs: extract-version

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: flake8 Lint
        uses: py-actions/flake8@v2

  editorconfig:
    runs-on: ubuntu-latest
    needs: extract-version

    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Markdown files
        uses: davidanson/markdownlint-cli2-action@v3
