name: lint

on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        required: true
        type: string
        description: "Python version to use"

jobs:

  flake8-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: flake8 Lint
        uses: py-actions/flake8@v2

  editorconfig:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Markdown files
        uses: davidanson/markdownlint-cli2-action@v3
