name: CI

on:
  push:
    branches:
      - master

jobs:
  extract-versions:
    uses: ./.github/workflows/extract-versions.yml

  lint:
    needs: [ extract-versions ]
    uses: ./.github/workflows/lint.yml
    with:
      PYTHON_VERSION: ${{ needs.extract-versions.outputs.PYTHON_VERSION }}

  build:
    needs: [ lint, extract-versions ]
    uses: ./.github/workflows/build.yml
    with:
      PYTHON_VERSION: ${{ needs.extract-versions.outputs.PYTHON_VERSION }}

  validate-build:
    needs: [ build, extract-versions ]
    permissions:
      contents: read
      actions: read

    uses: ./.github/workflows/validate-build.yml
    with:
      PYTHON_VERSION: ${{ needs.extract-versions.outputs.PYTHON_VERSION }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker:
    needs: [ validate-build, extract-versions ]
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Download Src Directory
        uses: actions/download-artifact@v4
        with:
          name: src

      - name: Download Dockerfile
        uses: actions/download-artifact@v4
        with:
          name: Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Dockerhub Tag
        run: |
          app_version="${{ needs.extract-versions.outputs.APP_VERSION }}"
          dockerhub_tag="${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT }}:${app_version}"
          echo "Dockerhub Tag: ${dockerhub_tag}"
          echo "DOCKERHUB_TAG=${dockerhub_tag}" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKERHUB_TAG }}
          build-args: |
            GIT_COMMIT=${{ env.GIT_COMMIT }}
