name: terminate

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY:
        description: 'AWS Access Key'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true

jobs:
  terminate:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Read EC2 Instance ID
        run: |
          INSTANCE_ID=$(cat ec2_instance_id.txt)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

      - name: Terminate EC2 Instance
        run: |
          aws ec2 terminate-instances --instance-ids ${{ env.INSTANCE_ID }}
          aws ec2 wait instance-terminated --instance-ids ${{ env.INSTANCE_ID }}
          echo "EC2 instance ${{ env.INSTANCE_ID }} terminated."
